const ADD_ARTICLE = 'ADD_ARTICLE'
const DELETE_ARTICLE = 'DELETE_ARTICLE'
const EDIT_ARTICLE = 'EDIT_ARTICLE'
const SAVE_ARTICLE = 'SAVE_ARTICLE'
const BUY_ITEM = 'BUY_ITEM'

export default {
    ADD_ARTICLE,
    DELETE_ARTICLE,
    EDIT_ARTICLE,
    SAVE_ARTICLE,
    BUY_ITEM
}